Repository hpaulosilva/devops-aula07, pull requests merged in 2018-09, with the labels that each got.

#2 Integrar requisitos v1.0
  docs/requisitos.md
Labels: analise

#7 Integrar implementação v1.0
  src/jogovelha.py
Labels: programação

#8 Integrar testes v1.0
  src/testes_inic.py
  src/testes_jogar.py
Labels: testes

#14 V1.1 programacao #12
  src/jogovelha.py
Labels: programação

#15 V1.1 testes #13
  docs/arquitetura.md
  docs/requisitos.md
  src/jogovelha.py
  src/testes_inic.py
  src/testes_jogar.py
Labels: testes

#16 #10
  docs/requisitos.md
Labels: analise

#17 #13
  src/testes_jogar.py
Labels: testes

#19 Integrar arquitetura v1.1
  docs/arquitetura.md
Labels: arquitetura

#21 Gerar release v1.1
  docs/arquitetura.md
  docs/requisitos.md
  src/jogovelha.py
  src/testes_jogar.py
Labels: operações
